import { Product, Farmer, PriceTickerItem, Order, Savings, Alert } from '../types';

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'بندورة بلدية',
    farmerId: 'f1',
    farmerName: 'مزرعة أبو أحمد',
    farmerAvatar: 'https://i.pravatar.cc/100?img=12',
    image: 'https://images.unsplash.com/photo-1546470427-e4c4d7961bba?w=400',
    retailPrice: 3.0,
    wholesalePrice: 2.2,
    marketPrice: 5.0,
    unit: 'كغ',
    available: 150,
    harvestDate: 'اليوم الصبح',
    isOrganic: true,
    isFresh: true,
    origin: 'فلسطيني المنشأ',
    rating: 4.8,
    reviewCount: 120,
    category: 'خضار',
    savings: 40,
  },
  {
    id: '2',
    name: 'خيار بيوت',
    farmerId: 'f2',
    farmerName: 'تعاونية برقين',
    farmerAvatar: 'https://i.pravatar.cc/100?img=15',
    image: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=400',
    retailPrice: 2.0,
    wholesalePrice: 1.5,
    marketPrice: 4.0,
    unit: 'كغ',
    available: 200,
    harvestDate: 'أمس',
    isOrganic: false,
    isFresh: true,
    origin: 'فلسطيني المنشأ',
    rating: 4.6,
    reviewCount: 85,
    category: 'خضار',
    savings: 50,
  },
  {
    id: '3',
    name: 'زيت زيتون نابلسي أصلي',
    farmerId: 'f3',
    farmerName: 'أبو محمود النابلسي',
    farmerAvatar: 'https://i.pravatar.cc/100?img=20',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400',
    retailPrice: 3.0,
    wholesalePrice: 2.5,
    marketPrice: 5.0,
    unit: 'ليتر',
    available: 60,
    harvestDate: 'موسم 2025',
    isOrganic: true,
    isFresh: false,
    origin: 'فلسطيني المنشأ',
    rating: 4.9,
    reviewCount: 200,
    category: 'زيوت',
    savings: 40,
  },
  {
    id: '4',
    name: 'بطاطا محلية',
    farmerId: 'f1',
    farmerName: 'مزرعة أبو أحمد',
    farmerAvatar: 'https://i.pravatar.cc/100?img=12',
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=400',
    retailPrice: 2.5,
    wholesalePrice: 1.8,
    marketPrice: 4.0,
    unit: 'كغ',
    available: 300,
    harvestDate: 'هاد الأسبوع',
    isOrganic: false,
    isFresh: true,
    origin: 'فلسطيني المنشأ',
    rating: 4.5,
    reviewCount: 60,
    category: 'خضار',
    savings: 37,
  },
];

export const mockFarmers: Farmer[] = [
  {
    id: 'f1',
    name: 'مزرعة الحاج أبو صبري',
    avatar: 'https://i.pravatar.cc/100?img=12',
    rating: 4.9,
    reviewCount: 340,
    distance: 1.2,
    isVerified: true,
    location: { latitude: 32.2211, longitude: 35.2544 },
    story: 'مزرعة عائلية بعمر 40 سنة في قلب سهل مرج بن عامر. نزرع بدون مبيدات منذ 2010.',
    specialty: ['بندورة', 'خيار', 'فليفلة'],
    totalProducts: 12,
  },
  {
    id: 'f2',
    name: 'تعاونية جذور الخير',
    avatar: 'https://i.pravatar.cc/100?img=15',
    rating: 4.7,
    reviewCount: 180,
    distance: 3.5,
    isVerified: true,
    location: { latitude: 32.33, longitude: 35.18 },
    story: 'تعاونية تضم 15 مزارعاً صغيراً من منطقة برقين. نعمل معاً لنقدم أفضل الأسعار.',
    specialty: ['خيار', 'كوسا', 'باذنجان'],
    totalProducts: 8,
  },
];

export const mockPriceTicker: PriceTickerItem[] = [
  { name: 'بندورة', price: 3.0, change: 'down', symbol: '₪' },
  { name: 'خيار', price: 2.0, change: 'flat', symbol: '₪' },
  { name: 'بطاطا', price: 4.0, change: 'up', symbol: '₪' },
  { name: 'كوسا', price: 5.0, change: 'down', symbol: '₪' },
  { name: 'فليفلة', price: 6.0, change: 'up', symbol: '₪' },
  { name: 'باذنجان', price: 3.5, change: 'down', symbol: '₪' },
];

export const mockOrders: Order[] = [
  {
    id: 'ORD-82739',
    status: 'preparing',
    farmerName: 'أبو أحمد',
    farmerAvatar: 'https://i.pravatar.cc/100?img=12',
    farmerPhone: '+970591234567',
    items: [{ name: 'بندورة بلدية', qty: 2, price: 3.0 }],
    total: 120.0,
    estimatedArrival: '11:15 AM',
    placedAt: '10:30 AM',
    address: 'رام الله، شارع الإرسال',
  },
];

export const mockSavings: Savings = {
  thisMonth: 47,
  totalOrders: 12,
  totalSaved: 183,
  rank: 'حارس الأرض',
  points: 340,
  nextRank: 'فلاح الموسم',
  pointsToNext: 160,
};

export const mockAlerts: Alert[] = [
  {
    id: 'a1',
    type: 'warning',
    message: '5 كيلو بندورة لم تُبع — فكّر بعرض سريع',
    action: 'إنشاء عرض الآن',
    actionRoute: '/farmer/flash-deal',
  },
  {
    id: 'a2',
    type: 'info',
    message: 'سعر الخيار في السوق انخفض 12% — عدّل سعرك',
    action: 'تعديل السعر',
    actionRoute: '/farmer/products',
  },
];
